import { Router } from "express";
import { archiveExperiment, archiveProject, createExperimentController, createProjectController, executeRun, getExperiment, getProject, getRun, listExperimentsController, listProjectsController, listRunsController, patchExperiment, patchProject, reproduceRun } from "../controllers/projectExperiment.controller.js";
import { requireAuthentication, requireExperimentRunWorkspace, requireExperimentWorkspace, requireProjectWorkspace, requireWorkspaceRole } from "../middleware/auth.js";
import { validateExperimentBody, validateExperimentPatch, validateExperimentRunBody, validateObjectId, validateProjectBody, validateProjectPatch } from "../middleware/validation.js";
const write = ["OWNER", "ADMIN", "RESEARCHER"], read = [...write, "VIEWER"];
const router = Router(); router.use(requireAuthentication);
router.post("/workspaces/:workspaceId/projects", requireWorkspaceRole(write), validateProjectBody, createProjectController);
router.get("/workspaces/:workspaceId/projects", requireWorkspaceRole(read), listProjectsController);
router.get("/projects/:id", validateObjectId("id"), requireProjectWorkspace(read), getProject);
router.patch("/projects/:id", validateObjectId("id"), requireProjectWorkspace(write), validateProjectPatch, patchProject);
router.post("/projects/:id/archive", validateObjectId("id"), requireProjectWorkspace(write), archiveProject);
router.post("/projects/:projectId/experiments", validateObjectId("projectId"), requireProjectWorkspace(write, "projectId"), validateExperimentBody, createExperimentController);
router.get("/projects/:projectId/experiments", validateObjectId("projectId"), requireProjectWorkspace(read, "projectId"), listExperimentsController);
router.get("/experiments/:id", validateObjectId("id"), requireExperimentWorkspace(read), getExperiment);
router.patch("/experiments/:id", validateObjectId("id"), requireExperimentWorkspace(write), validateExperimentPatch, patchExperiment);
router.post("/experiments/:id/archive", validateObjectId("id"), requireExperimentWorkspace(write), archiveExperiment);
router.post("/experiments/:id/runs", validateObjectId("id"), requireExperimentWorkspace(write), validateExperimentRunBody, executeRun);
router.get("/experiments/:id/runs", validateObjectId("id"), requireExperimentWorkspace(read), listRunsController);
router.get("/experiment-runs/:id", validateObjectId("id"), requireExperimentRunWorkspace(read), getRun);
router.post("/experiment-runs/:id/reproduce", validateObjectId("id"), requireExperimentRunWorkspace(write), reproduceRun);
export default router;
