/**
 * ProvenanceChain
 *
 * Visual step-chain showing the data flow from mission inputs through to
 * integrity verification. Based on a lightweight W3C PROV-DM model:
 *
 *   Entity (Input Parameters)
 *     wasUsedBy ↓
 *   Activity (Analysis Run)
 *     wasGeneratedBy ↓
 *   Entity (Risk / Environment / Orbital Models)
 *     wasGeneratedBy ↓
 *   Entity (Research Record)
 *     wasGeneratedBy ↓
 *   Activity (Canonicalization)
 *     wasGeneratedBy ↓
 *   Entity (SHA-256 Digest)
 *     wasGeneratedBy ↓
 *   Activity (Verification)
 *
 * Props:
 *   missionName         — string
 *   analysisRunId       — string | null
 *   modelVersion        — string | null
 *   canonicalizationVersion — string | null
 *   integrityHash       — string | null  (truncated in display)
 *   verificationStatus  — "VERIFIED" | "FAILED" | "PENDING" | "NOT_VERIFIED" | "UNAVAILABLE"
 */

const DEFAULT_STEPS = [
  {
    key: "input",
    entityType: "Entity",
    provNotation: "prov:Entity",
    label: "INPUT PARAMETERS",
    name: "Mission Orbital Parameters",
    desc:
      "Altitude, inclination, and duration defined at mission creation.",
    dotState: "complete"
  },
  {
    key: "analysis",
    entityType: "Activity",
    provNotation: "prov:Activity",
    label: "ANALYSIS RUN",
    name: "Deterministic Analysis Engine",
    desc:
      "Orbital mechanics, risk factors, and environmental exposure are computed using the OrbitForge analysis model.",
    dotState: "complete"
  },
  {
    key: "models",
    entityType: "Entity",
    provNotation: "prov:Entity",
    label: "MODEL OUTPUTS",
    name: "Risk · Environment · Orbital Models",
    desc:
      "Scored risk factors, environmental exposure factors, and orbital characteristics generated by the analysis run.",
    dotState: "complete"
  },
  {
    key: "record",
    entityType: "Entity",
    provNotation: "prov:Entity",
    label: "RESEARCH RECORD",
    name: "Structured Research Record",
    desc:
      "Mission intelligence, risk assessment, and provenance metadata assembled into a canonical research record.",
    dotState: "active"
  },
  {
    key: "canon",
    entityType: "Activity",
    provNotation: "prov:Activity",
    label: "CANONICALIZATION",
    name: "Deterministic Serialization",
    desc:
      "The research record is serialized to a canonical byte sequence to ensure a reproducible digest.",
    dotState: "active"
  },
  {
    key: "hash",
    entityType: "Entity",
    provNotation: "prov:Entity",
    label: "SHA-256 DIGEST",
    name: "Integrity Hash",
    desc:
      "The SHA-256 digest of the canonical record. Used to detect changes to the stored record content.",
    dotState: "active"
  },
  {
    key: "verification",
    entityType: "Activity",
    provNotation: "prov:Activity",
    label: "VERIFICATION",
    name: "Integrity Verification",
    desc:
      "The record is re-serialized and re-hashed. The computed digest is compared to the stored digest to confirm integrity.",
    dotState: "terminal"
  }
];

function truncateHash(hash, chars = 20) {
  if (!hash) return null;
  if (hash.length <= chars * 2 + 3) return hash;
  return `${hash.slice(0, chars)}…${hash.slice(-8)}`;
}

function StepConnector({ dotState }) {
  return (
    <div className="provenance-chain__step-connector">
      <div
        className={`provenance-chain__step-dot provenance-chain__step-dot--${dotState}`}
      />
      <div className="provenance-chain__step-line" />
    </div>
  );
}

function ProvenanceChain({
  missionName,
  analysisRunId,
  modelVersion,
  canonicalizationVersion,
  integrityHash,
  verificationStatus
}) {
  const steps = DEFAULT_STEPS.map(step => ({ ...step }));

  const isUnavailable = verificationStatus === "UNAVAILABLE";

  return (
    <div className="provenance-chain">
      <div className="provenance-chain__header">
        <span className="provenance-chain__kicker">
          W3C PROV-DM / LIGHTWEIGHT PROVENANCE
        </span>

        <h3 className="provenance-chain__title">
          Analysis Provenance Chain
        </h3>

        <p className="provenance-chain__caption">
          Traces the data lineage from orbital input parameters through
          analysis, research record creation, and integrity verification.
        </p>
      </div>

      <ol className="provenance-chain__steps" aria-label="Provenance chain steps">
        {steps.map((step) => {
          /* Inject live data into specific steps */
          let meta = null;

          if (step.key === "analysis" && analysisRunId) {
            meta = `Run ID: ${analysisRunId}`;
          }

          if (step.key === "models" && modelVersion) {
            meta = `Model v${modelVersion}`;
          }

          if (step.key === "canon" && canonicalizationVersion) {
            meta = `Canon v${canonicalizationVersion}`;
          }

          if (step.key === "hash" && integrityHash) {
            meta = truncateHash(integrityHash);
          }

          if (step.key === "record" && missionName) {
            meta = missionName;
          }

          /* Adjust verification dot state based on actual status */
          let dotState = step.dotState;

          if (isUnavailable && ["record", "canon", "hash", "verification"].includes(step.key)) {
            dotState = "terminal";
          } else if (step.key === "verification" && verificationStatus) {
            if (verificationStatus === "VERIFIED") {
              dotState = "complete";
            } else if (verificationStatus === "FAILED") {
              dotState = "active";
            }
          }

          const isStepUnavailable = isUnavailable && ["record", "canon", "hash", "verification"].includes(step.key);

          return (
            <li
              key={step.key}
              className="provenance-chain__step"
            >
              <StepConnector dotState={dotState} />

              <div className="provenance-chain__step-body">
                <span className="provenance-chain__step-label">
                  {isStepUnavailable ? `${step.label} (UNAVAILABLE)` : step.label}
                </span>

                <span className="provenance-chain__step-name">
                  {step.name}
                </span>

                <p className="provenance-chain__step-desc">
                  {step.desc}
                </p>

                <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginTop: "6px" }}>
                  <span className="provenance-chain__prov-notation">
                    {step.provNotation}
                  </span>

                  {meta && (
                    <span className="provenance-chain__step-meta">
                      {meta}
                    </span>
                  )}
                </div>
              </div>
            </li>
          );
        })}
      </ol>
    </div>
  );
}

export default ProvenanceChain;
